from django.shortcuts import render
import random
citas = [
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. – Robert Collier",
    "La vida es lo que pasa mientras estás ocupado haciendo otros planes. – John Lennon",
    "Sé el cambio que quieres ver en el mundo.– Mahatma Gandhi",
    "El único modo de hacer un gran trabajo es amar lo que haces.– Steve Jobs",
    "No esperes. El tiempo nunca será justo.– Napoleon Hill",
    "La vida es como montar en bicicleta. Para mantener el equilibrio, debes seguir adelante.– Albert Einstein",
    "Nunca es demasiado tarde para ser lo que podrías haber sido.– George Eliot",
    "Todo lo que puedes imaginar es real.– Pablo Picasso",
    "El coraje no siempre ruge. A veces, es una pequeña voz al final del día que dice: 'Lo intentaré de nuevo mañana.'– Mary Anne Radmacher",
    "La felicidad no es algo listo. Viene de tus propias acciones.– Dalai Lama",
    "El fracaso es el condimento que da al éxito su sabor.– Truman Capote",
    "La creatividad es inteligencia divirtiéndose.– Albert Einstein",
    "La mejor manera de predecir el futuro es crearlo.– Peter Drucker",
    "No cuentes los días, haz que los días cuenten.– Muhammad Ali",
    "Los desafíos son lo que hacen la vida interesante; superarlos es lo que la hace significativa.– Joshua J. Marine",
    "La gente más feliz no es la que tiene lo mejor de todo, sino la que hace lo mejor con lo que tiene.– Helen Keller",
    "El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.– Marcel Proust",
    "El secreto de la vida es caer siete veces y levantarse ocho.– Paulo Coelho",
    "Tu tiempo es limitado, no lo malgastes viviendo la vida de otro.– Steve Jobs",
    "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor de continuar.– Winston Churchill",
    "Cree que puedes y estarás a mitad de camino.– Theodore Roosevelt",
    "Hazlo con pasión o no lo hagas.– Rosa Nouchette Carey",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.– Albert Schweitzer",
    "No tengas miedo de renunciar a lo bueno para ir por lo grandioso.– John D. Rockefeller",
    "El mayor error que puedes cometer en la vida es tener miedo continuamente de cometer uno.– Elbert Hubbard",
    "El arte de ser sabio es el arte de saber qué pasar por alto.– William James",
    "La vida es realmente simple, pero insistimos en hacerla complicada.– Confucio",
    "El optimismo perpetuo es un multiplicador de fuerza.– Colin Powell",
    "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.– Henry Ford",
    "No se trata de cuántas veces te derriban, sino de cuántas veces te levantas.– Vince Lombardi",
    "El éxito parece estar conectado con la acción. Las personas exitosas se mantienen en movimiento.– Conrad Hilton",
    "La mejor forma de predecir el futuro es inventarlo.– Alan Kay",
    "La vida es 10% lo que me sucede y 90% cómo reacciono ante ello.– Charles Swindoll",
    "Si puedes soñarlo, puedes hacerlo.– Walt Disney",
    "El poder de la imaginación nos hace infinitos.– John Muir",
    "A veces la caída es una forma de aprender a volar.– Victor Hugo",
    "Lo que obtienes al alcanzar tus metas no es tan importante como en quién te conviertes al alcanzarlas.– Henry David Thoreau",
    "Es mejor fracasar en la originalidad que tener éxito en la imitación.– Herman Melville",
    "El éxito no se mide por lo que logras, sino por los obstáculos que superas.– Booker T. Washington",
    "El coraje es resistencia al miedo, dominio del miedo, no ausencia de miedo.– Mark Twain",
    "La vida no se trata de esperar a que pase la tormenta, sino de aprender a bailar bajo la lluvia.– Vivian Greene",
    "La única forma de hacer un gran trabajo es amar lo que haces.– Steve Jobs",
    "El conocimiento habla, pero la sabiduría escucha.– Jimi Hendrix",
    "Cuida tus pensamientos, se convierten en palabras. Cuida tus palabras, se convierten en acciones. Cuida tus acciones, se convierten en hábitos. Cuida tus hábitos, se convierten en carácter. Cuida tu carácter, se convierte en tu destino.– Lao-Tse",
    "El genio es 1% inspiración y 99% transpiración.– Thomas Edison",
    "La adversidad es una oportunidad para el crecimiento.– Malcolm X",
    "El único límite a nuestra realización del mañana son nuestras dudas de hoy.– Franklin D. Roosevelt",
    "El verdadero éxito no está en vencer siempre, sino en no darse por vencido nunca.– Napoleón Bonaparte",
    "Nunca dudes de que un pequeño grupo de ciudadanos comprometidos puede cambiar el mundo; de hecho, es lo único que lo ha hecho.– Margaret Mead",
    "Haz que cada día sea tu obra maestra.– John Wooden",
    "El futuro pertenece a aquellos que creen en la belleza de sus sueños.– Eleanor Roosevelt",
    "No dejes que los miedos se interpongan en el camino de tus sueños.– Babe Ruth",
    "Un día sin risa es un día perdido.– Charlie Chaplin",
    "La vida es corta, pero siempre hay tiempo suficiente para la cortesía.– Ralph Waldo Emerson",
    "El coraje es la resistencia al miedo, el dominio del miedo, no la ausencia de miedo.– Mark Twain",
    "Lo que hacemos en la vida tiene su eco en la eternidad.– Máximo (Gladiator)",
    "Cuida el presente, porque en él vivirás el resto de tu vida.– Facundo Cabral",
    "El pasado no puede ser cambiado. El futuro está todavía en tu poder.– Desconocido",
    "Cada día es una nueva oportunidad para cambiar tu vida.– Desconocido",
    "La vida es como una cámara, enfoca en lo que es importante, captura los buenos momentos, desarrolla de los negativos, y si las cosas no salen bien, toma otra toma.– Desconocido",
    "El mayor placer en la vida es hacer lo que la gente dice que no puedes hacer.– Walter Bagehot",
    "Siempre parece imposible hasta que se hace.– Nelson Mandela",
    "El éxito es el resultado de la preparación, el trabajo duro y aprender del fracaso.– Colin Powell",
    "La felicidad es una dirección, no un lugar.– Sydney J. Harris",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.– Vidal Sassoon",
    "El fracaso no es el opuesto al éxito; es parte del éxito.– Arianna Huffington",
    "El coraje es descubrir que puedes no tener razón, pero aún así seguir adelante.– Maya Angelou",
    "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.– Winston Churchill",
    "El propósito de la vida es contribuir de alguna manera a hacer las cosas mejores.– Robert F. Kennedy",
    "Vive como si fueras a morir mañana. Aprende como si fueras a vivir siempre.– Mahatma Gandhi",
    "No cuentes tus días, haz que tus días cuenten.– Muhammad Ali",
    "Cada día es una nueva oportunidad para cambiar tu vida.– Desconocido",
    "El secreto para salir adelante es empezar.– Mark Twain",
    "El poder de la imaginación nos hace infinitos.– John Muir",
    "Lo que no te mata te hace más fuerte.– Friedrich Nietzsche",
    "Haz todo el bien que puedas, por todos los medios que puedas, en todos los lugares que puedas.– John Wesley",
    "El fracaso es una excelente oportunidad para empezar de nuevo con más inteligencia.– Henry Ford",
    "La vida no se trata de encontrarte a ti mismo, se trata de crearte a ti mismo.– George Bernard Shaw",
    "Tu única limitación es tu mente.– Napoleon Hill",
    "El genio es 1% inspiración y 99% transpiración.– Thomas Edison",
    "Haz lo que puedas, con lo que tengas, donde estés.– Theodore Roosevelt",
    "El futuro depende de lo que hagas hoy.– Mahatma Gandhi",
    "No eres el producto de tus circunstancias. Eres el producto de tus decisiones.– Stephen Covey",
    "No te detengas cuando estés cansado, detente cuando hayas terminado.– Desconocido",
    "El éxito es la habilidad de ir de un fracaso a otro sin perder el entusiasmo.– Winston Churchill",
    "El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.– Proverbio chino",
    "Nunca es demasiado tarde para ser lo que podrías haber sido.– George Eliot",
    "La vida es corta, pero siempre hay tiempo suficiente para la cortesía.– Ralph Waldo Emerson",
    "El éxito no es final, el fracaso no es fatal: lo que cuenta es el coraje para continuar.– Winston Churchill",
    "No vivas la misma vida durante 75 años y llámalo vida.– Robin Sharma",
    "El éxito no se mide por lo que logras, sino por los obstáculos que superas.– Booker T. Washington",
    "El arte de ser sabio es saber qué pasar por alto.– William James",
    "Si no puedes volar, corre. Si no puedes correr, camina. Si no puedes caminar, arrástrate. Pero sea lo que hagas, sigue avanzando.– Martin Luther King Jr.",
    "El éxito no es un destino, es un viaje.– Zig Ziglar",
    "Cree que puedes y estarás a mitad de camino.– Theodore Roosevelt",
    "El secreto de salir adelante es empezar.– Mark Twain",
    "Las oportunidades no ocurren, las creas.– Chris Grosser",
    "El verdadero fracaso es no intentarlo.– George Clooney",
    "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor de continuar.– Winston Churchill",
    "El futuro pertenece a quienes creen en la belleza de sus sueños.– Eleanor Roosevelt",
]
def generarCita():
    cita = random.choice(citas)
    return cita

def home(request):
    cita = generarCita()
    context = {
        'cita':cita,
    }
    return render(request, "index.html",context)